POST http://localhost:8000/sign-up
Content-Type: application/json

{
    "name" : "Amen dhahri",
    "username": "Amen",
    "email": "a@a.c",
    "password": "amen"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "userid" : "a@o.c",
    "password" : "password"
}

###

GET http://localhost:8000/getposts

###

POST http://localhost:8000/create
Content-Type: application/json

{
  "userid": 2,
  "content": "Second user second post"
}

###

PUT http://localhost:8000/posts/
Content-Type: application/json

{
  "content": "second user third post lol :)"
}


###
DELETE http://localhost:8000/delete/3


###

GET http://localhost:8000/getuser/1

